[versions]
coroutinesReactor = "1.7.3"
dependencyManagement = "1.1.7"
kotest = "5.8.0"
kotlin = "2.1.0"
reactor = "3.5.0"
springBoot = "3.5.0"
springContext = "6.2.7"
mockk-jvm = "1.13.3"
supabase = "3.2.5"
ktor = "3.2.0"
viaduct = "0.4.0"
java-jwt = "4.4.0"

[plugins]
dependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
viaduct-application = { id = "com.airbnb.viaduct.application-gradle-plugin", version.ref = "viaduct" }
viaduct-module = { id = "com.airbnb.viaduct.module-gradle-plugin", version.ref = "viaduct" }

[libraries]
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "coroutinesReactor" }
reactor-core = { group = "io.projectreactor", name = "reactor-core", version.ref = "reactor" }
spring-boot-starter-graphql = { group = "org.springframework.boot", name = "spring-boot-starter-graphql" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-context = { group = "org.springframework", name = "spring-context", version.ref = "springContext" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
kotest-runner-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json", version.ref = "kotest" }
io-mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk-jvm" }
io-mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk-jvm" }
supabase-postgrest-kt = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt", version.ref = "supabase" }
supabase-auth-kt = { group = "io.github.jan-tennert.supabase", name = "gotrue-kt", version.ref = "supabase" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
viaduct-service-wiring = { group = "com.airbnb.viaduct", name = "service-wiring", version.ref = "viaduct" }
java-jwt = { group = "com.auth0", name = "java-jwt", version.ref = "java-jwt" }
